---
- name: Apache http
  hosts: all
  tasks: 
  - name: Install httpd package
    yum: 
      name: httpd
      state: present
  - name: Start httpd service
    service: 
      name: httpd
      state: started
